// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giangbbimymuzyaehemt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpYW5nYmJpbXltdXp5YWVoZW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODA4MTQsImV4cCI6MjA3NDM1NjgxNH0.mSK2Q0wgD6jrgqDfm4sibm5CTFZbKoxuGF1VX5fougo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});